[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install && cd apps/web && pnpm run build"
watchPatterns = ["apps/web/**", "packages/**"]

[deploy]
startCommand = "cd apps/web && npx serve dist -l 3000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3000"