[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install && cd apps/api && pnpm run build"

[deploy]
startCommand = "cd apps/api && pnpm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "3001"
NODE_ENV = "production"